### ISSUE TITLE
MGMT: Build failure w/ Unexpected value 'MdTabsModule'

### ISSUE THREAD

**Issue by mmoayyed** [Unicon/cas#50]
From: https://travis-ci.org/apereo/cas/jobs/284148540

```
Date: 2017-10-06T11:41:51.353Z
Hash: e7d69d9bebec3c792528
Time: 8707ms
chunk {0} styles.f4d1bf31c4f7cff048ee.bundle.css (styles) 44.5 kB {3} [initial] [rendered]
chunk {1} polyfills.3bc34265385d52184eab.bundle.js (polyfills) 86 bytes {3} [initial] [rendered]
chunk {2} main.e402deade8b026b7d50e.bundle.js (main) 84 bytes [initial] [rendered]
chunk {3} inline.8c3d4d4604a3d1fec8f8.bundle.js (inline) 1.45 kB [entry] [rendered]
ERROR in Error: Unexpected value 'MdTabsModule in /home/travis/build/apereo/cas/webapp-mgmt/cas-management-webapp/node_modules/@angular/material/material.d.ts' imported by the module 'SharedModule in /home/travis/build/apereo/cas/webapp-mgmt/cas-management-webapp/src/app/shared/shared.module.ts'. Please add a @NgModule annotation.
    at syntaxError (/home/travis/build/apereo/cas/webapp-mgmt/cas-management-webapp/node_modules/@angular/compiler/bundles/compiler.umd.js:1729:34)
    at /home/travis/build/apereo/cas/webapp-mgmt/cas-management-webapp/node_modules/@angular/compiler/bundles/compiler.umd.js:15582:44
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/home/travis/build/apereo/cas/webapp-mgmt/cas-management-webapp/node_modules/@angular/compiler/bundles/compiler.umd.js:15565:49)
    at addNgModule (/home/travis/build/apereo/cas/webapp-mgmt/cas-management-webapp/node_modules/@angular/compiler/bundles/compiler.umd.js:24408:58)
    at /home/travis/build/apereo/cas/webapp-mgmt/cas-management-webapp/node_modules/@angular/compiler/bundles/compiler.umd.js:24419:14
    at Array.forEach (native)
    at _createNgModules (/home/travis/build/apereo/cas/webapp-mgmt/cas-management-webapp/node_modules/@angular/compiler/bundles/compiler.umd.js:24418:26)
    at analyzeNgModules (/home/travis/build/apereo/cas/webapp-mgmt/cas-management-webapp/node_modules/@angular/compiler/bundles/compiler.umd.js:24293:14)
    at analyzeAndValidateNgModules (/home/travis/build/apereo/cas/webapp-mgmt/cas-management-webapp/node_modules/@angular/compiler/bundles/compiler.umd.js:24303:35)
    at AotCompiler.analyzeModulesAsync (/home/travis/build/apereo/cas/webapp-mgmt/cas-management-webapp/node_modules/@angular/compiler/bundles/compiler.umd.js:23937:46)
    at CodeGenerator.codegen (/home/travis/build/apereo/cas/webapp-mgmt/cas-management-webapp/node_modules/@angular/compiler-cli/src/codegen.js:32:14)
    at Function.NgTools_InternalApi_NG_2.codeGen (/home/travis/build/apereo/cas/webapp-mgmt/cas-management-webapp/node_modules/@angular/compiler-cli/src/ngtools_api.js:73:30)
    at _donePromise.Promise.resolve.then (/home/travis/build/apereo/cas/webapp-mgmt/cas-management-webapp/node_modules/@ngtools/webpack/src/plugin.js:386:44)
npm ERR! Linux 4.4.0-93-generic
npm ERR! argv "/home/travis/build/apereo/cas/webapp-mgmt/cas-management-webapp/.gradle/nodejs/node-v7.10.0-linux-x64/bin/node" "/home/travis/build/apereo/cas/webapp-mgmt/cas-management-webapp/.gradle/nodejs/node-v7.10.0-linux-x64/bin/npm" "run" "build"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cas-management-angular-webapp@0.0.0 build: `ng build --prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cas-management-angular-webapp@0.0.0 build script 'ng build --prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cas-management-angular-webapp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng build --prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cas-management-angular-webapp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cas-management-angular-webapp
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/.npm/_logs/2017-10-06T11_41_51_412Z-debug.log
:webapp-mgmt:cas-management-webapp:buildClient FAILED
:autoLintGradle
```

**Comment by tsschmidt** [comment]
Ok, looks like latest material update change the module names to MatMODULE_NAME instead of MdMODULE_NAME.  I will get a PR to merge soon.


________________________________

**Comment by tsschmidt** [comment]
Fix has been pushed to mgmt-material-refactor.

**Comment by mmoayyed** [comment]
Passing build. Merged. Deleted branch. Thank you!

**Comment by tsschmidt** [comment]
Do I need to merge this into the tooltip PR before it can be merged?

________________________________

**Comment by mmoayyed** [comment]
No, but if you would be better to merge apereo/cas:master into this branch so the PR can rebuild itself and pass green.

**Comment by tsschmidt** [comment]
will do

________________________________
